services:
  prometheus:
    # Accessible on port 9090
    image: prom/prometheus:main-distroless
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - storage_prometheus:/prometheus
    network_mode: host
  
  grafana:
    # Accessible on port 3000
    image: grafana/grafana:10.4.4
    environment:
      GF_SERVER_ROOT_URL: "http://127.0.0.1:3000"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWD}
    volumes:
      - storage_grafana:/var/lib/grafana
      - ./grafana/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/provider.yml:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json:ro
    network_mode: host
    depends_on:
      - prometheus

volumes:
  storage_grafana:
  storage_prometheus:

